### PR TITLE
Add performance testing with lighthouse

### LINKED ISSUE #4: Add performance testing
- Start with LightHouse
- Use either `--perf` flag our custom config file to run only the performance tests
- Run a control test first to figure out the performance of the environment
- Use a hard-coded threshold score value for now
- Only local Chrome in Travis

See Manolos prototype for inspiration: https://github.com/vaadin/vaadin-context-menu/compare/proto/perf-tests

### PR DESCRIPTION
**Pull request by platosha**
Fixes #4

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-input/14)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 25 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-input/14#-KcIWvu3jB4zRVbTvEXg:-KcIWvu3jB4zRVbTvEXh:b-veosk1) ([raw file](https://github.com/vaadin/vaadin-input/blob/51c6d24b34a1a73b1c4bcb83f5939aafcae71a3e/.travis.yml#L25)):*
> ```YAML
> script:
>   - ([ "$TRAVIS_EVENT_TYPE" = "pull_request" ] || gemini test test/visual)
>   - LIGHTHOUSE_CHROMIUM_PATH="`which google-chrome-stable`" xvfb-run -s '-screen 0 1024x768x24' node test/performance/test.js
> ```

why do we need this? when running lighthouse it should figure out the path or the chrome browser, or  are there different versions of chrome installed in travis ?

---

*[package.json, line 33 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-input/14#-KcIXMvNK8_wgB9r27Zm:-KcIXMvNK8_wgB9r27Zn:b-4lkdpw) ([raw file](https://github.com/vaadin/vaadin-input/blob/51c6d24b34a1a73b1c4bcb83f5939aafcae71a3e/package.json#L33)):*
> ```JSON
>     "gulp-html-extract": "^0.0.3",
>     "gulp-stylelint": "^3.7.0",
>     "lighthouse": "~1.2.2",
> ```

Why this version? what are the issues of latest ?

---

*[test/performance/test.js, line 1 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-input/14#-KcIXj7hnC9VudPSp0nB:-KcIXj7hnC9VudPSp0nC:bt64t50) ([raw file](https://github.com/vaadin/vaadin-input/blob/51c6d24b34a1a73b1c4bcb83f5939aafcae71a3e/test/performance/test.js#L1)):*
> ```JavaScript
> const minimumPerformanceThreshold = 0.625;
> ```

From where this value come from ? 
Don't we need a control test anymore ?

---

*[test/performance/test.js, line 51 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-input/14#-KcIYNxO7Pu2RSSnZgj6:-KcIYNxO7Pu2RSSnZgj7:b-5j7cbv) ([raw file](https://github.com/vaadin/vaadin-input/blob/51c6d24b34a1a73b1c4bcb83f5939aafcae71a3e/test/performance/test.js#L51)):*
> ```JavaScript
> }
> 
> function dequeueNextTest() {
> ```

Why are you using promises, tests must be run synchronously to avoid performance interferences.
I would use `execSync` instead and simplify the code removing promises

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-input/14)*

**Comment by manolo** [comment]
BTW, we could have a gulp task instead of a external script ?

---

Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-input/14#-:-KcIZ2c1yWFfsdvJYh8e:b-qatkec)*

**Comment by Saulis** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[test/performance/test.js, line 1 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-input/14#-KcIXj7hnC9VudPSp0nB:-KcIjbAeQgSeyHZQT_sl:bbjanhz) ([raw file](https://github.com/vaadin/vaadin-input/blob/51c6d24b34a1a73b1c4bcb83f5939aafcae71a3e/test/performance/test.js#L1)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

From where this value come from ? 
Don't we need a control test anymore ?
</blockquote></details>

No, we don't since the throttling works nicely after all. Currently the test scores 0.78 - 0.81 so we could maybe ramp up this threshold to 0.75?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-input/14)*

**Comment by platosha** [comment]
@manolo maybe, but I personally don't see a purpose in gulp for that. Will it give any benefits?

---

Reviewed 1 of 4 files at r1.
Review status: 1 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 25 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-input/14#-KcIWvu3jB4zRVbTvEXg:-KcJ2qz8L2Dp7fBDU8tI:b-y3coxa) ([raw file](https://github.com/vaadin/vaadin-input/blob/51c6d24b34a1a73b1c4bcb83f5939aafcae71a3e/.travis.yml#L25)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

why do we need this? when running lighthouse it should figure out the path or the chrome browser, or  are there different versions of chrome installed in travis ?
</blockquote></details>

This old lightlouse v1.2 I’m using here can’t automatically locate chrome on linux yet. :-(

---

*[package.json, line 33 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-input/14#-KcIXMvNK8_wgB9r27Zm:-KcJ31XQzSkekukk1TdE:b-5l4hpr) ([raw file](https://github.com/vaadin/vaadin-input/blob/51c6d24b34a1a73b1c4bcb83f5939aafcae71a3e/package.json#L33)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Why this version? what are the issues of latest ?
</blockquote></details>

- latest lighthouse has measurement problems with stable Chrome (gives low score due to errors of missing `firstMeaningfulPaint` event in Chrome trace. This is reproducible locally, and the event is indeed missing if I trace manually),
- ... but works well against Chrome Canary,
- ... but there is no Canary for linux,
- older lighthouse works well against stable Chrome now.

---

*[test/performance/test.js, line 1 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-input/14#-KcIXj7hnC9VudPSp0nB:-KcJ3lHhXtMFBOAYQ-BC:bm1xafy) ([raw file](https://github.com/vaadin/vaadin-input/blob/51c6d24b34a1a73b1c4bcb83f5939aafcae71a3e/test/performance/test.js#L1)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

No, we don't since the throttling works nicely after all. Currently the test scores 0.78 - 0.81 so we could maybe ramp up this threshold to 0.75?
</blockquote></details>

Increased to `.75`.

Control test is not needed, lighthouse has a pretty consistent score, it benchmarks itself.

---

*[test/performance/test.js, line 51 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-input/14#-KcIYNxO7Pu2RSSnZgj6:-KcJ4IinGFw7Fn_8_c6l:bfqcofq) ([raw file](https://github.com/vaadin/vaadin-input/blob/51c6d24b34a1a73b1c4bcb83f5939aafcae71a3e/test/performance/test.js#L51)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Why are you using promises, tests must be run synchronously to avoid performance interferences.
I would use `execSync` instead and simplify the code removing promises
</blockquote></details>

The script also runs `polyserve` in a single thread. Doing `execSync` with lighthouse locks this single thread, then polyserve is locked as well and not responding anything anymore.

Then it was easier to me to use `exec` for lighthouse then `fork` for polyserve.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-input/14#-:-KcJ2bsq1yZHdaWJuVCn:bx2e9w6)*

**Comment by manolo** [comment]
We are using gulp to centralise tasks that we need to run in our builds. To me it is easier to look at it, or just run `gulp --list`
Having a script in node otherwise, does not adds any benefit to have shell script, which indeed needs less code to maintain.

---

Review status: 1 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[test/performance/test.js, line 1 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-input/14#-KcIXj7hnC9VudPSp0nB:-KcJsAjpTEqAAmTeMtXY:b-t8j47s) ([raw file](https://github.com/vaadin/vaadin-input/blob/51c6d24b34a1a73b1c4bcb83f5939aafcae71a3e/test/performance/test.js#L1)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Increased to `.75`.

Control test is not needed, lighthouse has a pretty consistent score, it benchmarks itself.
</blockquote></details>

So probably unstable results I got was because the lighthouse version. Nice that we can have one version with reproducible results.

If we have more tests for instance measuring how fast load demo page, probably we need to maintain a table with different threshold per test, but not now.

---

*[test/performance/test.js, line 51 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-input/14#-KcIYNxO7Pu2RSSnZgj6:-KcJsiXp9LgNH7sAr2RL:b5jjzai) ([raw file](https://github.com/vaadin/vaadin-input/blob/51c6d24b34a1a73b1c4bcb83f5939aafcae71a3e/test/performance/test.js#L51)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

The script also runs `polyserve` in a single thread. Doing `execSync` with lighthouse locks this single thread, then polyserve is locked as well and not responding anything anymore.

Then it was easier to me to use `exec` for lighthouse then `fork` for polyserve.
</blockquote></details>

But you can run `polyserve.then( synchronous-exec here) `

If we use gulp, I guess task flow should be easier than having to manage our own promise queue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-input/14#-:-KcJqutpAyRZL857XmCd:b6hb184)*

**Comment by Saulis** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-input/14#-:-KcMLF0sWI3oBx2lobNI:bnfp4nl)*

**Comment by platosha** [comment]
Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/performance/test.js, line 51 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-input/14#-KcIYNxO7Pu2RSSnZgj6:-KcXBrDUR8LCpbR6maEt:b-896fix) ([raw file](https://github.com/vaadin/vaadin-input/blob/51c6d24b34a1a73b1c4bcb83f5939aafcae71a3e/test/performance/test.js#L51)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

But you can run `polyserve.then( synchronous-exec here) `

If we use gulp, I guess task flow should be easier than having to manage our own promise queue.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-input/14)*

**Comment by limonte** [comment]
I like the output in Travis build log :+1:

:lgtm:

---

Review status: 2 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-input/14#-:-KcXCb3RM6TqHMCYq6EB:bwm5g5b)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r1, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-input/14#-:-KcXD9otn6KGlKsCYV13:bnfp4nl)*

**Comment by manolo** [comment]
Reviewed 1 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-input/14)*

**Pull request merged**
