### PR TITLE
Focus input on label-click. Fixes #31

### LINKED ISSUE #31: Clicking the label focuses the host element instead of the input (Chrome)

### PR DESCRIPTION
**Pull request by manolo**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-input/33)

### CODE REVIEW

**Comment by Saulis** [comment]
Adding `for="input"` doesn't prevent the host element from being temporarily focused which gives a nasty outline blink. Also, it's possible to click on the host element without clicking the label or the input: 


I'd propose listening for `click` events on the host element and then manually focusing the input.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-input/33#-:-Ke3F6tkbUdc6yz7-Vgk:b-xao4sk)*

**Comment by manolo** [comment]
Just CSSing the outline is enough for not having the blinking border.

I would rather not add code about events, listening to `click` does not prevent the blinking effect, but it fixes clicking in a different area.

So probably if we want to fix all cases we need the `outline: none`, `click => focus()`, `label for=`. I'm not 100% positive about the click solution, elements extending control-state might have other focusable/clickable elements in its dom tree.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-input/33#-:-Ke3b6jikw-0pOid5hda:b95w8qg)*

**Comment by Saulis** [comment]
I don't think we have any choice not to add the event listeners because currently the focus is lost when you click outside the input (and label)

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-input/33#-:-Ke8_YRANvSAlzOJgGHh:bc427wa)*

**Comment by manolo** [comment]
Done.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-input/33#-:-Ke9CTpcryRpXsxK_9OX:b-896fix)*

**Comment by platosha** [comment]
One more bug in Safari, focus highlight is not removed when defocusing by clicking outside the input:

1. open material design demo in Safari
2. focus an input
3. click somewhere else to remove the focus

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-control-state-mixin.html, line 62 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-input/33#-KeIP03RXgPProW22tCs:-KeIP03RXgPProW22tCt:b-7gvmx9) ([raw file](https://github.com/vaadin/vaadin-input/blob/165e61d5de65dace0d00bc187197ee0d51e121de/vaadin-control-state-mixin.html#L62)):*
> ```HTML
>       this.addEventListener('focus', e => this._focus(e));
>       this.addEventListener('blur', () => this._setFocused(false));
>       this.addEventListener('click', e => this._focus(e));
> ```

Normally the focus happens after `mousedown` already, the following `click` is pretty late. Can we use `mousedown` here?

---

*[vaadin-input.html, line 71 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-input/33#-KeIOklQwvxREwMUFtVA:-KeIOklQwvxREwMUFtVB:b2fwsol) ([raw file](https://github.com/vaadin/vaadin-input/blob/165e61d5de65dace0d00bc187197ee0d51e121de/vaadin-input.html#L71)):*
> ```HTML
>     </style>
> 
>     <label id="label" for="input" on-click="focus">[[label]]</label>
> ```

In Shady DOM ids are global, `for="input"` always focuses the first input on the page. Happens in Safari at least. Steps:

1. open material design demos in safari
2. click 3rd input’s label
3. first input is focused. 3rd input is highlighted, but does not have focus.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-input/33#-:-KeIPbGoudTOG5qqj-z6:b-n1aaro)*

**Comment by manolo** [comment]
> One more bug in Safari, focus highlight is not removed when defocusing by clicking outside the input:

Apparently It was failing before this PR. We we did a refactoring we thought the listener should be set to the host element. Moving the listener to the focusable internal element fixes it.

Done

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-control-state-mixin.html, line 62 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-input/33#-KeIP03RXgPProW22tCs:-KeIVpqW7GEuJ6Pn5mdV:b-7bdf4x) ([raw file](https://github.com/vaadin/vaadin-input/blob/165e61d5de65dace0d00bc187197ee0d51e121de/vaadin-control-state-mixin.html#L62)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Normally the focus happens after `mousedown` already, the following `click` is pretty late. Can we use `mousedown` here?
</blockquote></details>

We need to move the focus, once the focus has actually been set to any element in the component. 
The only way to do in mousedown is preventing, but we don't want to do that.

---

*[vaadin-input.html, line 71 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-input/33#-KeIOklQwvxREwMUFtVA:-KeIWFn-A1BInldSVIg3:b-896fix) ([raw file](https://github.com/vaadin/vaadin-input/blob/165e61d5de65dace0d00bc187197ee0d51e121de/vaadin-input.html#L71)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

In Shady DOM ids are global, `for="input"` always focuses the first input on the page. Happens in Safari at least. Steps:

1. open material design demos in safari
2. click 3rd input’s label
3. first input is focused. 3rd input is highlighted, but does not have focus.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-input/33#-:-KeIV8XX65DG5qeruxLx:b-6t83gh)*

**Comment by platosha** [comment]
When defocusing with Shift+Tab, the focus highlight is not removed. Hapens in both Chrome and Safari, does not happen in master.

For all these focus and blur cases, should we maybe add tests?

---

Reviewed 2 of 3 files at r2.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-input/33#-:-KeJ5m58W0mHAGp1BIyx:b-j7bj8r)*

**Comment by platosha** [comment]
Reviewed 1 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-input/33)*

**Comment by manolo** [comment]
Test for blur is quite difficult. The only reliable way is in shadow dom when you can blur natively. I already spent a lot of time trying to make blur tests work in FF

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-input/33#-:-KeJ85-9JK8HN9Um2SwU:bcpkhp9)*

**Comment by manolo** [comment]
Shift+Tab should work correctly now

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-input/33#-:-KeJTKsL89HAZTPOETWv:b-qt9xqm)*

**Comment by Saulis** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-input/33#-:-KeJXoeGe7d7x8RaPjiX:bnfp4nl)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-input/33#-:-KeY0_rqDeok198i6T_O:bnfp4nl)*

**Pull request merged**
