### PR TITLE
Feature/label

### LINKED ISSUE #5: Add label
- Label position should be definable by CSS
  - separate positions can be defined for states: input empty/non-empty, focused 
- Default position for the label is on top of the field (like `always-float-label` on `<paper-input>`
- Consider support for form-layout

### PR DESCRIPTION
**Pull request by manolo**
Fixes #5 

@jouni label styling in MD theme is just to make it work. You might want different properties.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-input/19)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Styling demo looks broken on iOS Safari

---

Review status: 0 of 16 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-input.html, line 10 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-input/19#-Kd5X-egzuVryuZaMtAh:-Kd5X-egzuVryuZaMtAi:b-1daoig) ([raw file](https://github.com/vaadin/vaadin-input/blob/8d3907bfd62652d1af31a6baa9c20da8b3dd0206/vaadin-input.html#L10)):*
> ```HTML
> `<vaadin-input>` is a Polymer element for input control in forms.
> 
> It wraps an `<input>` and a `<label>` native elements easy to customize.
> ```

Doesn't sound right

---

*[vaadin-input.html, line 65 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-input/19#-Kd5Yw2t-Wu4gw_SpaPe:-Kd5Yw2t-Wu4gw_SpaPf:b-2je2tv) ([raw file](https://github.com/vaadin/vaadin-input/blob/8d3907bfd62652d1af31a6baa9c20da8b3dd0206/vaadin-input.html#L65)):*
> ```HTML
>     </style>
> 
>     <dom-if if="[[label]]">
> ```

Dom-if is an overkill for this. Use `hidden` instead like so:
https://github.com/PolymerElements/paper-input/blob/master/paper-input.html#L110

---

*[vaadin-input.html, line 126 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-input/19#-Kd5YOTA0dAn95x-niJP:-Kd5YOTA0dAn95x-niJQ:bs7n3f3) ([raw file](https://github.com/vaadin/vaadin-input/blob/8d3907bfd62652d1af31a6baa9c20da8b3dd0206/vaadin-input.html#L126)):*
> ```HTML
> 
>             /**
>              * String used for the label element. If empty the element is removed from the dom.
> ```

"If empty the element is removed from the dom.", this is internal technical detail that shouldn't concern the user/developer. Can be removed.

---

*[demo/material-vaadin-input.html, line 99 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-input/19#-Kd5ZlOpriuD3PBOJmRO:-Kd5ZlOpriuD3PBOJmRP:b1v6lb) ([raw file](https://github.com/vaadin/vaadin-input/blob/8d3907bfd62652d1af31a6baa9c20da8b3dd0206/demo/material-vaadin-input.html#L99)):*
> ```HTML
>           transform: translateY(0);
>           color: #3F51B5;
>           font-size: 14px;
> ```

This will shrink the label, which causes the layout to wobble.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-input/19#-:-Kd5WpT9u7vjNqtWYv5d:b2sotiz)*

**Comment by jouni** [comment]
Review status: 0 of 17 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-input.html, line 65 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-input/19#-Kd5Yw2t-Wu4gw_SpaPe:-KdAUPs3BODmzlfTX6MG:b-nws5up) ([raw file](https://github.com/vaadin/vaadin-input/blob/8d3907bfd62652d1af31a6baa9c20da8b3dd0206/vaadin-input.html#L65)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Dom-if is an overkill for this. Use `hidden` instead like so:
https://github.com/PolymerElements/paper-input/blob/master/paper-input.html#L110
</blockquote></details>

Removed. We agreed to not use `hidden` either (it didn’t even work with negative attribute bindings in Polymer 2), but instead leave the option for the theme developer to hide the empty label is needed.

---

*[demo/material-vaadin-input.html, line 99 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-input/19#-Kd5ZlOpriuD3PBOJmRO:-KdAUpwVhgDntjdUxc7o:bt2vr1b) ([raw file](https://github.com/vaadin/vaadin-input/blob/8d3907bfd62652d1af31a6baa9c20da8b3dd0206/demo/material-vaadin-input.html#L99)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

This will shrink the label, which causes the layout to wobble.
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-input/19)*

**Comment by manolo** [comment]
Review status: 0 of 17 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[vaadin-input.html, line 10 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-input/19#-Kd5X-egzuVryuZaMtAh:-KdAynACGQ9lVBTgmfxc:bss4a2b) ([raw file](https://github.com/vaadin/vaadin-input/blob/8d3907bfd62652d1af31a6baa9c20da8b3dd0206/vaadin-input.html#L10)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Doesn't sound right
</blockquote></details>

Removed.

---

*[vaadin-input.html, line 65 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-input/19#-Kd5Yw2t-Wu4gw_SpaPe:-KdAypV91BUILoSQ63tx:b-896fix) ([raw file](https://github.com/vaadin/vaadin-input/blob/8d3907bfd62652d1af31a6baa9c20da8b3dd0206/vaadin-input.html#L65)):*
<details><summary><i>Previously, jouni (Jouni Koivuviita) wrote…</i></summary><blockquote>

Removed. We agreed to not use `hidden` either (it didn’t even work with negative attribute bindings in Polymer 2), but instead leave the option for the theme developer to hide the empty label is needed.
</blockquote></details>

Done.

---

*[vaadin-input.html, line 126 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-input/19#-Kd5YOTA0dAn95x-niJP:-KdAyt2d4oyMR9jJeQGi:b-896fix) ([raw file](https://github.com/vaadin/vaadin-input/blob/8d3907bfd62652d1af31a6baa9c20da8b3dd0206/vaadin-input.html#L126)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

"If empty the element is removed from the dom.", this is internal technical detail that shouldn't concern the user/developer. Can be removed.
</blockquote></details>

Done.

---

*[vaadin-input.html, line 302 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-input/19#-KdB7Dja2rQtIX0pzv7Z:-KdB7Dja2rQtIX0pzv7_:bpnktj6) ([raw file](https://github.com/vaadin/vaadin-input/blob/e740160ba3e91fdbe047e75576709e7608fc5d40/vaadin-input.html#L302)):*
> ```HTML
>       // (already shipping in Edge Preview)
>       attributeChangedCallback(prop, oldVal, newVal) {
>         super.attributeChangedCallback(prop, oldVal, newVal);
> ```

@jouni optimised this observer so as we only penalise Edge

---

*[demo/material-vaadin-input.html, line 99 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-input/19#-Kd5ZlOpriuD3PBOJmRO:-KdAytxtdT9trGH4RSeQ:b-896fix) ([raw file](https://github.com/vaadin/vaadin-input/blob/8d3907bfd62652d1af31a6baa9c20da8b3dd0206/demo/material-vaadin-input.html#L99)):*
<details><summary><i>Previously, jouni (Jouni Koivuviita) wrote…</i></summary><blockquote>

Fixed.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-input/19)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r2, 2 of 12 files at r3, 2 of 12 files at r4, 14 of 14 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-input/19#-:-Kde8fV7iMG9DdSDjYPs:bnfp4nl)*

**Pull request merged**
